
load_module modules/ngx_http_modsecurity_module.so;

worker_processes auto;

events {
    worker_connections 1024;
}


http {
    lua_shared_dict feature_extraction_log_locks 1m;
    lua_shared_dict detection_log_locks 1m;

    # Lua modules in ./lua relative to project root
    lua_package_path "lua/?.lua;;";

    # Logs relative to project root
    log_format waf_json escape=json
      '{ "ip":"$remote_addr", '
      '"method":"$request_method", '
      '"uri":"$request_uri", '
      '"status":$status }';

    access_log logs/access.log waf_json;
    error_log  logs/error.log info;

    upstream backend {
        server 127.0.0.1:3000;
    }

    server {
        

        listen 8080;
        
        rewrite_by_lua_block {
        ngx.req.set_header("X-WAF-Request-ID", ngx.var.request_id)
        local feature_main = require("feature_extraction.main")
        feature_main.run()
        }
        
        
        
        modsecurity on;

        
        modsecurity_rules_file modsec/modsecurity.conf;
        
        location /request_id {
            return 200 "$request_id";
        }
        
        location / {
            # Lua WAF file relative to project root
            access_by_lua_file lua/detection/waf.lua;
            proxy_pass http://backend;
        }
        
    }
}
