
load_module modules/ngx_http_modsecurity_module.so;

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Lua modules in ./lua relative to project root
    lua_package_path "lua/?.lua;;";

    # Logs relative to project root
    log_format waf_json escape=json
      '{ "ip":"$remote_addr", '
      '"method":"$request_method", '
      '"uri":"$request_uri", '
      '"status":$status }';

    access_log logs/access.log waf_json;
    error_log  logs/error.log info;

    upstream backend {
        server 127.0.0.1:3000;
    }

    server {
        

        listen 8080;
        # modsecurity on;
        # modsecurity_rules_file modsec/modsecurity.conf;
        location / {
            # Lua WAF file relative to project root
            access_by_lua_file lua/waf.lua;
            proxy_pass http://backend;
        }
    }
}
