



SecRuleEngine On

SecRequestBodyAccess On
SecResponseBodyAccess Off


SecRuleEngine DetectionOnly

# Audit logging
SecAuditEngine on
SecAuditLog logs/modsec_audit.log
SecAuditLogFormat JSON

# Log enough parts to reconstruct the request and rule matches
SecAuditLogParts ABIJHZ

# Include CRS
Include modsec/owasp-crs/crs-setup.conf
Include modsec/owasp-crs/rules/*.conf